# docker-compose.yml
version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: tpopova/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    image: tpopova/foodgram_frontend
    volumes:
      - static:/app/result_build/

  gateway:
    image: tpopova/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - "7000:80"
